namespace SimpleProblemsApi.Features.EulerProblems.Services
{
    public class FibonacciSumService : IProblemService
    {
        public string GetDescription()
        {
            return "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        }

        public long GetSolution(long highestValue)
        {
            var element = 2;
            var previousElements = new[] { 1, 2 };
            var sum = 0;

            while (element < highestValue)
            {
                if (IsEven(element))
                {
                    sum += element;
                }

                element = previousElements[0] + previousElements[1];
                previousElements[0] = previousElements[1];
                previousElements[1] = element;
            }

            return sum;
        }

        private bool IsEven(long inputToCheck)
        {
            return inputToCheck % 2 == 0;
        }
    }
}